### ISSUE TITLE
Multipart request validation

### ISSUE THREAD

**Issue by domenicomusto** [openrasta/openrasta-core#2] opened 2011-04-27 10:22 UTC
Hi,

currently when the multipart request is wrong (boundary messed up) openrasta returns 500 

System.InvalidOperationException: The operation is not ready for invocation.
   at OpenRasta.OperationModel.MethodBased.MethodBasedOperation.Invoke() in d:\dev\git-repos\openrasta-stable\src\core\OpenRasta\OperationModel\MethodBased\MethodBasedOperation.cs:line 58
   at OpenRasta.OperationModel.Interceptors.OperationWithInterceptors.&lt;Invoke&gt;b__0() in d:\dev\git-repos\openrasta-stable\src\core\OpenRasta\OperationModel\Interceptors\OperationWithInterceptors.cs:line 47
   at OpenRasta.OperationModel.Interceptors.OperationWithInterceptors.Invoke() in d:\dev\git-repos\openrasta-stable\src\core\OpenRasta\OperationModel\Interceptors\OperationWithInterceptors.cs:line 52
   at OpenRasta.OperationModel.OperationExecutor.Execute(IEnumerable`1 operations) in d:\dev\git-repos\openrasta-stable\src\core\OpenRasta\OperationModel\OperationExecutor.cs:line 14
   at OpenRasta.Pipeline.Contributors.OperationInvokerContributor.ExecuteOperations(ICommunicationContext context) in d:\dev\git-repos\openrasta-stable\src\core\OpenRasta\Pipeline\Contributors\OperationInvokerContributor.cs:line 29
   at OpenRasta.Pipeline.PipelineRunner.ExecuteContributor(ICommunicationContext context, ContributorCall call) in d:\dev\git-repos\openrasta-stable\src\core\OpenRasta\Pipeline\PipelineRunner.cs:line 192

Is it possible to have back a 400 bad request ? 

tnx

Domenico

**Comment by serialseb** [comment] 2017-05-24 21:31
Hi there.

Thanks for reporting this issue! It's awesome of you to have taken the time.

It seems that this issue may be a duplicate of #8, so in the interest of keeping our backlog lean ⛅, I'm closing the issue in favour of the other one.

If you feel this is not right, don't hesitate to comment and/or reopen the issue.

Thanks!

**Closed by serialseb** 2017-05-24 21:31 UTC
